version: "3.5"
services:
  db:
    image: postgres
    container_name: "my_db"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "my_app"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

